# -*- coding: utf-8 -*-
# =============================================================================
# facettes.py
# =============================================================================
#
# Author:      Dorian Grosch
# E-Mail:      dorian.grosch@sbb.spk-berlin.de
# Institution: Staatsbibliothek zu Berlin
#
# =============================================================================

"""
LLM output schema for facet extraction.

Used by core.inference.facettes module.
"""

from pydantic import BaseModel, Field
from typing import List, Optional
from enum import Enum


class MediaForms(str, Enum):
    """
    Media form types for library catalog filtering.
    Sources:
        stabikat.de
    """
    ARTICLE_PRINT = "Article"
    ARTICLE_ONLINE = "electronic Article"
    BOOK_PRINT = "Book"
    DATA_MEDIA = "Data Media"
    E_BOOK = "eBook"
    E_JOURNAL = "eJournal"
    GAME = "Game"
    JOURNAL_PRINT = "Journal"
    MANUSCRIPT = "Manuscript"
    MAP = "Map"
    MICROFORM = "Microform"
    MIXED_MATERIALS = "Mixed Materials"
    MONOGRAPH_SERIES = "Monograph Series"
    MOTION_PICTURE = "Motion Picture"
    MUSICAL_SCORE = "Musical Score"
    PICTURE = "Picture"
    PROJECTED_MEDIUM = "Projected Medium"
    SERIAL_VOLUME = "Serial Volume"
    SOUND_RECORDING = "Sound Recording"


class ContentGenre(str, Enum):
    """
    Content genre types for library catalog filtering.
    Sources:
        https://sta.dnb.de/doc/RDA-VW-E-W075-LISTE-1
        https://sta.dnb.de/doc/RDA-VW-E-W075-LISTE-2
    """
    IMPLEMENTATION_PROVISIONS = "Ausführungsbestimmungen"
    ADDRESS_BOOK = "Adressbuch"
    ANTHOLOGY = "Anthologie"
    ATLAS = "Atlas"
    PROBLEM_SET = "Aufgabensammlung"
    COLLECTION_OF_ESSAYS = "Aufsatzsammlung"
    EXHIBITION_CATALOG = "Ausstellungskatalog"
    AUTOBIOGRAPHY = "Autobiografie"
    COLLECTION_OF_EXAMPLES = "Beispielsammlung"
    BIBLIOGRAPHY = "Bibliografie"
    PICTURE_BOOK = "Bilderbuch"
    BIOGRAPHY = "Biografie"
    LETTER = "Brief"
    DATA_COLLECTION = "Datensammlung"
    DIAGRAM = "Diagramm"
    DISSERTATION = "Dissertation"
    SCREENPLAY = "Drehbuch"
    BROADSHEET = "Einblattdruck"
    INTRODUCTION = "Einführung"
    ENCYCLOPEDIA = "Enzyklopädie"
    TIMETABLE = "Fahrplan"
    FACSIMILE = "Faksimile"
    CASE_STUDY_COLLECTION = "Fallstudiensammlung"
    FESTSCHRIFT = "Festschrift"
    FICTIONAL_REPRESENTATION = "Fiktionale Darstellung"
    FLYER = "Flugblatt"
    RESEARCH_REPORT = "Forschungsbericht"
    PHOTOGRAPH = "Fotografie"
    GUIDE = "Führer"
    CONVERSATION = "Gespräch"
    GRAPHIC_ART = "Grafik"
    ACADEMIC_PUBLICATION = "Hochschulschrift"
    INTERVIEW = "Interview"
    INVENTORY = "Inventar"
    JUVENILE_BOOK = "Jugendbuch"
    JUVENILE_NON_FICTION = "Jugendsachbuch"
    CALENDAR = "Kalender"
    MAP = "Karte"
    CATALOG = "Katalog"
    CHILDRENS_BOOK = "Kinderbuch"
    COMMENTARY = "Kommentar"
    CONFERENCE_PROCEEDINGS = "Konferenzschrift"
    CONCORDANCE = "Konkordanz"
    ARTISTS_BOOK = "Künstlerbuch"
    ART_GUIDE = "Kunstführer"
    TEXTBOOK = "Lehrbuch"
    TEACHING_AND_LEARNING_RESOURCE = "Lehr- und Lernressource"
    EDUCATIONAL_SOFTWARE = "Lernsoftware"
    READER = "Lesebuch"
    LITERATURE_REPORT = "Literaturbericht"
    MODEL = "Modell"
    STANDARD = "Norm"
    GAZETTEER = "Ortsverzeichnis"
    PAPYRUS = "Papyrus"
    POSTER = "Plakat"
    PLAN = "Plan"
    PRIVATE_PRESS_PRINT = "Pressendruck"
    SOURCE = "Quelle"
    GUIDEBOOK = "Ratgeber"
    ABSTRACTING_JOURNAL = "Referateorgan"
    ABSTRACT_OF_DEED = "Regest"
    STATUTE = "Satzung"
    SCHEMATISM = "Schematismus"
    SCHOOL_TEXTBOOK = "Schulbuch"
    GAME = "Spiel"
    FEATURE_FILM = "Spielfilm"
    CITY_MAP = "Stadtplan"
    PLATE = "Tafel"
    PLAY = "Theaterstück"
    EXERCISE_COLLECTION = "Übungssammlung"
    SURVEY = "Umfrage"
    CHARTER = "Urkunde"
    SALES_CATALOG = "Verkaufskatalog"
    DIRECTORY = "Verzeichnis"
    CATALOGUE_RAISONNE = "Werkverzeichnis"
    HOUSE_JOURNAL = "Werkzeitschrift"
    DICTIONARY = "Wörterbuch"
    DRAWING = "Zeichnung"


class Language(str, Enum):
    """
    Language types for library catalog filtering.
    Sources:
        stabikat.de
    """
    ABKHAZ = "Abkhaz"
    ACHINESE = "Achinese"
    ACOLI = "Acoli"
    ADYGEI = "Adygei"
    AFAR = "Afar"
    AFRIKAANS = "Afrikaans"
    AFROASIATIC_OTHER = "Afroasiatic (Other)"
    AKAN = "Akan"
    AKKADIAN = "Akkadian"
    ALBANIAN = "Albanian"
    ALEUT = "Aleut"
    ALGONQUIAN_OTHER = "Algonquian (Other)"
    ALTAIC_OTHER = "Altaic (Other)"
    AMHARIC = "Amharic"
    APACHE_LANGUAGES = "Apache languages"
    ARABIC = "Arabic"
    ARAGONESE_SPANISH = "Aragonese Spanish"
    ARAMAIC = "Aramaic"
    ARAPAHO = "Arapaho"
    ARAWAK = "Arawak"
    ARMENIAN = "Armenian"
    ARTIFICIAL_OTHER = "Artificial (Other)"
    ASSAMESE = "Assamese"
    ATHAPASCAN_OTHER = "Athapascan (Other)"
    AUSTRALIAN_LANGUAGES = "Australian languages"
    AUSTRONESIAN_OTHER = "Austronesian (Other)"
    AVARIC = "Avaric"
    AVESTAN = "Avestan"
    AWADHI = "Awadhi"
    AYMARA = "Aymara"
    AZERBAIJANI = "Azerbaijani"
    BABLE = "Bable"
    BALINESE = "Balinese"
    BALTIC_OTHER = "Baltic (Other)"
    BALUCHI = "Baluchi"
    BAMBARA = "Bambara"
    BANTU_OTHER = "Bantu (Other)"
    BASA = "Basa"
    BASHKIR = "Bashkir"
    BASQUE = "Basque"
    BATAK = "Batak"
    BEJA = "Beja"
    BELARUSIAN = "Belarusian"
    BEMBA = "Bemba"
    BENGALI = "Bengali"
    BERBER_OTHER = "Berber (Other)"
    BHOJPURI = "Bhojpuri"
    BIHARI = "Bihari"
    BIKOL = "Bikol"
    BISLAMA = "Bislama"
    BOSNIAN = "Bosnian"
    BRAJ = "Braj"
    BRETON = "Breton"
    BUGIS = "Bugis"
    BULGARIAN = "Bulgarian"
    BURIAT = "Buriat"
    BURMESE = "Burmese"
    CADDO = "Caddo"
    CARIB = "Carib"
    CATALAN = "Catalan"
    CAUCASIAN_OTHER = "Caucasian (Other)"
    CEBUANO = "Cebuano"
    CELTIC_OTHER = "Celtic (Other)"
    CENTRAL_AMERICAN_INDIAN_OTHER = "Central American Indian (Other)"
    CHAGATAI = "Chagatai"
    CHAMIC_LANGUAGES = "Chamic languages"
    CHAMORRO = "Chamorro"
    CHECHEN = "Chechen"
    CHEROKEE = "Cherokee"
    CHEYENNE = "Cheyenne"
    CHIBCHA = "Chibcha"
    CHINESE = "Chinese"
    CHINOOK_JARGON = "Chinook jargon"
    CHIPEWYAN = "Chipewyan"
    CHOCTAW = "Choctaw"
    CHURCH_SLAVIC = "Church Slavic"
    CHUVASH = "Chuvash"
    COPTIC = "Coptic"
    CORNISH = "Cornish"
    CORSICAN = "Corsican"
    CREE = "Cree"
    CREEK = "Creek"
    CREOLES_AND_PIDGINS_ENGLISH_BASED = "Creoles and Pidgins, English-based (Other)"
    CREOLES_AND_PIDGINS_FRENCH_BASED = "Creoles and Pidgins, French-based (Other)"
    CREOLES_AND_PIDGINS_OTHER = "Creoles and Pidgins (Other)"
    CREOLES_AND_PIDGINS_PORTUGUESE_BASED = "Creoles and Pidgins, Portuguese-based (Other)"
    CRIMEAN_TATAR = "Crimean Tatar"
    CROATIAN = "Croatian"
    CUSHITIC_OTHER = "Cushitic (Other)"
    CZECH = "Czech"
    DAKOTA = "Dakota"
    DANISH = "Danish"
    DARGWA = "Dargwa"
    DAYAK = "Dayak"
    DELAWARE = "Delaware"
    DINKA = "Dinka"
    DIVEHI = "Divehi"
    DOGRI = "Dogri"
    DRAVIDIAN_OTHER = "Dravidian (Other)"
    DUALA = "Duala"
    DUTCH = "Dutch"
    DUTCH_MIDDLE = "Dutch, Middle (ca. 1050-1350)"
    DZONGKHA = "Dzongkha"
    EDO = "Edo"
    EFIK = "Efik"
    EGYPTIAN = "Egyptian"
    ELAMITE = "Elamite"
    ENGLISH = "English"
    ENGLISH_MIDDLE = "English, Middle (1100-1500)"
    ENGLISH_OLD = "English, Old (ca. 450-1100)"
    ESKIMO_LANGUAGES = "Eskimo languages"
    ESPERANTO = "Esperanto"
    ESTONIAN = "Estonian"
    ETHIOPIC = "Ethiopic"
    EWE = "Ewe"
    EWONDO = "Ewondo"
    FANG = "Fang"
    FANTI = "Fanti"
    FAROESE = "Faroese"
    FIJIAN = "Fijian"
    FINNISH = "Finnish"
    FINNO_UGRIAN_OTHER = "Finno-Ugrian (Other)"
    FON = "Fon"
    FRENCH = "French"
    FRENCH_MIDDLE = "French, Middle (ca. 1400-1600)"
    FRENCH_OLD = "French, Old (ca. 842-1400)"
    FRISIAN = "Frisian"
    FRIULIAN = "Friulian"
    FULA = "Fula"
    GA = "Ga"
    GALICIAN = "Galician"
    GANDA = "Ganda"
    GAYO = "Gayo"
    GBAYA = "Gbaya"
    GEORGIAN = "Georgian"
    GERMAN = "German"
    GERMAN_MIDDLE_HIGH = "German, Middle High (ca. 1050-1500)"
    GERMAN_OLD_HIGH = "German, Old High (ca. 750-1050)"
    GERMANIC_OTHER = "Germanic (Other)"
    GILBERTESE = "Gilbertese"
    GONDI = "Gondi"
    GOTHIC = "Gothic"
    GREBO = "Grebo"
    GREEK_ANCIENT = "Greek, Ancient (to 1453)"
    GREEK_MODERN = "Greek, Modern (1453- )"
    GUARANI = "Guarani"
    GUJARATI = "Gujarati"
    GWICHIN = "Gwich'in"
    HAIDA = "Haida"
    HAITIAN_FRENCH_CREOLE = "Haitian French Creole"
    HAUSA = "Hausa"
    HAWAIIAN = "Hawaiian"
    HEBREW = "Hebrew"
    HERERO = "Herero"
    HILIGAYNON = "Hiligaynon"
    HIMACHALI = "Himachali"
    HINDI = "Hindi"
    HIRI_MOTU = "Hiri Motu"
    HITTITE = "Hittite"
    HMONG = "Hmong"
    HUNGARIAN = "Hungarian"
    IBAN = "Iban"
    ICELANDIC = "Icelandic"
    IDO = "Ido"
    IGBO = "Igbo"
    IJO = "Ijo"
    ILOKO = "Iloko"
    INDIC_OTHER = "Indic (Other)"
    INDO_EUROPEAN_OTHER = "Indo-European (Other)"
    INDONESIAN = "Indonesian"
    INGUSH = "Ingush"
    INTERLINGUA = "Interlingua (International Auxiliary Language Association)"
    INTERLINGUE = "Interlingue"
    INUKTITUT = "Inuktitut"
    INUPIAQ = "Inupiaq"
    IRANIAN_OTHER = "Iranian (Other)"
    IRISH = "Irish"
    IRISH_MIDDLE = "Irish, Middle (ca. 1100-1550)"
    IRISH_OLD = "Irish, Old (to 1100)"
    IROQUOIAN_OTHER = "Iroquoian (Other)"
    ITALIAN = "Italian"
    JAPANESE = "Japanese"
    JAVANESE = "Javanese"
    JUDEO_ARABIC = "Judeo-Arabic"
    JUDEO_PERSIAN = "Judeo-Persian"
    KABARDIAN = "Kabardian"
    KABYLE = "Kabyle"
    KACHIN = "Kachin"
    KALATDLISUT = "Kalatdlisut"
    KALMYK = "Kalmyk"
    KAMBA = "Kamba"
    KANNADA = "Kannada"
    KANURI = "Kanuri"
    KARA_KALPAK = "Kara-Kalpak"
    KAREN = "Karen"
    KASHMIRI = "Kashmiri"
    KAWI = "Kawi"
    KAZAKH = "Kazakh"
    KHASI = "Khasi"
    KHMER = "Khmer"
    KHOISAN_OTHER = "Khoisan (Other)"
    KHOTANESE = "Khotanese"
    KIKUYU = "Kikuyu"
    KIMBUNDU = "Kimbundu"
    KINYARWANDA = "Kinyarwanda"
    KOMI = "Komi"
    KONGO = "Kongo"
    KONKANI = "Konkani"
    KOREAN = "Korean"
    KPELLE = "Kpelle"
    KRU = "Kru"
    KUANYAMA = "Kuanyama"
    KUMYK = "Kumyk"
    KURDISH = "Kurdish"
    KURUKH = "Kurukh"
    KUSAIE = "Kusaie"
    KYRGYZ = "Kyrgyz"
    LADINO = "Ladino"
    LAHNDA = "Lahnda"
    LAMBA = "Lamba"
    LAO = "Lao"
    LATIN = "Latin"
    LATVIAN = "Latvian"
    LETZEBURGESCH = "Letzeburgesch"
    LEZGIAN = "Lezgian"
    LIMBURGISH = "Limburgish"
    LINGALA = "Lingala"
    LITHUANIAN = "Lithuanian"
    LOW_GERMAN = "Low German"
    LOZI = "Lozi"
    LUBA_KATANGA = "Luba-Katanga"
    LUBA_LULUA = "Luba-Lulua"
    LUNDA = "Lunda"
    LUO = "Luo (Kenya and Tanzania)"
    LUSHAI = "Lushai"
    MACEDONIAN = "Macedonian"
    MADURESE = "Madurese"
    MAGAHI = "Magahi"
    MAITHILI = "Maithili"
    MAKASAR = "Makasar"
    MALAGASY = "Malagasy"
    MALAY = "Malay"
    MALAYALAM = "Malayalam"
    MALTESE = "Maltese"
    MANCHU = "Manchu"
    MANDAR = "Mandar"
    MANDINGO = "Mandingo"
    MANIPURI = "Manipuri"
    MANOBO_LANGUAGES = "Manobo languages"
    MANX = "Manx"
    MAORI = "Maori"
    MAPUCHE = "Mapuche"
    MARATHI = "Marathi"
    MARI = "Mari"
    MARSHALLELSE = "Marshallese"
    MARWARI = "Marwari"
    MASAI = "Masai"
    MAYAN_LANGUAGES = "Mayan languages"
    MENDE = "Mende"
    MICMAC = "Micmac"
    MINANGKABAU = "Minangkabau"
    MISCELLANEOUS_LANGUAGES = "Miscellaneous languages"
    MOHAWK = "Mohawk"
    MON_KHMER_OTHER = "Mon-Khmer (Other)"
    MONGO_NKUNDU = "Mongo-Nkundu"
    MONGOLIAN = "Mongolian"
    MOORE = "Moore"
    MULTIPLE_LANGUAGES = "Multiple languages"
    MUNDA_OTHER = "Munda (Other)"
    NAHUATL = "Nahuatl"
    NAURU = "Nauru"
    NAVAJO = "Navajo"
    NDEBELE_SOUTH_AFRICA = "Ndebele (South Africa)"
    NDEBELE_ZIMBABWE = "Ndebele (Zimbabwe)"
    NDONGA = "Ndonga"
    NEAPOLITAN_ITALIAN = "Neapolitan Italian"
    NEPALI = "Nepali"
    NEWARI = "Newari"
    NIAS = "Nias"
    NIGER_KORDOFANIAN_OTHER = "Niger-Kordofanian (Other)"
    NILO_SAHARAN_OTHER = "Nilo-Saharan (Other)"
    NIUEAN = "Niuean"
    NOGAI = "Nogai"
    NORTH_AMERICAN_INDIAN_OTHER = "North American Indian (Other)"
    NORTHERN_SAMI = "Northern Sami"
    NORTHERN_SOTHO = "Northern Sotho"
    NORWEGIAN = "Norwegian"
    NORWEGIAN_BOKMAL = "Norwegian (Bokmal)"
    NORWEGIAN_NYNORSK = "Norwegian (Nynorsk)"
    NUBIAN_LANGUAGES = "Nubian languages"
    NYAMWEZI = "Nyamwezi"
    NYANJA = "Nyanja"
    NYANKOLE = "Nyankole"
    OCCITAN = "Occitan (post-1500)"
    OJIBWA = "Ojibwa"
    OLD_NORSE = "Old Norse"
    OLD_PERSIAN = "Old Persian (ca. 600-400 B.C.)"
    ORIYA = "Oriya"
    OROMO = "Oromo"
    OSAGE = "Osage"
    OSSETIC = "Ossetic"
    OTOMIAN_LANGUAGES = "Otomian languages"
    PAHLAVI = "Pahlavi"
    PALAUAN = "Palauan"
    PALI = "Pali"
    PAMPANGA = "Pampanga"
    PANJABI = "Panjabi"
    PAPIAMENTO = "Papiamento"
    PAPUAN_OTHER = "Papuan (Other)"
    PERSIAN = "Persian"
    PHILIPPINE_OTHER = "Philippine (Other)"
    PHOENICIAN = "Phoenician"
    POLISH = "Polish"
    PONAPE = "Ponape"
    PORTUGUESE = "Portuguese"
    PRAKRIT_LANGUAGES = "Prakrit languages"
    PROVENCAL = "Provencal (to 1500)"
    PUSHTO = "Pushto"
    QUECHUA = "Quechua"
    RAETO_ROMANCE = "Raeto-Romance"
    RAJASTHANI = "Rajasthani"
    RAPANUI = "Rapanui"
    RAROTONGAN = "Rarotongan"
    ROMANCE_OTHER = "Romance (Other)"
    ROMANI = "Romani"
    ROMANIAN = "Romanian"
    RUNDI = "Rundi"
    RUSSIAN = "Russian"
    SALISHAN_LANGUAGES = "Salishan languages"
    SAMARITAN_ARAMAIC = "Samaritan Aramaic"
    SAMI = "Sami"
    SAMOAN = "Samoan"
    SANGO = "Sango (Ubangi Creole)"
    SANSKRIT = "Sanskrit"
    SANTALI = "Santali"
    SARDINIAN = "Sardinian"
    SASAK = "Sasak"
    SCOTS = "Scots"
    SCOTTISH_GAELIC = "Scottish Gaelic"
    SELKUP = "Selkup"
    SEMITIC_OTHER = "Semitic (Other)"
    SERBIAN = "Serbian"
    SERER = "Serer"
    SHAN = "Shan"
    SHONA = "Shona"
    SICHUAN_YI = "Sichuan Yi"
    SIDAMO = "Sidamo"
    SIKSIKA = "Siksika"
    SINDHI = "Sindhi"
    SINHALESE = "Sinhalese"
    SINO_TIBETAN_OTHER = "Sino-Tibetan (Other)"
    SIOUAN_OTHER = "Siouan (Other)"
    SKOLT_SAMI = "Skolt Sami"
    SLAVE = "Slave"
    SLAVIC_OTHER = "Slavic (Other)"
    SLOVAK = "Slovak"
    SLOVENIAN = "Slovenian"
    SOGDIAN = "Sogdian"
    SOMALI = "Somali"
    SONGHAI = "Songhai"
    SONINKE = "Soninke"
    SORBIAN_LANGUAGES = "Sorbian languages"
    SOTHO = "Sotho"
    SOUTH_AMERICAN_INDIAN_OTHER = "South American Indian (Other)"
    SOUTHERN_SAMI = "Southern Sami"
    SPANISH = "Spanish"
    SUKUMA = "Sukuma"
    SUMERIAN = "Sumerian"
    SUNDANESE = "Sundanese"
    SUSU = "Susu"
    SWAHILI = "Swahili"
    SWAZI = "Swazi"
    SWEDISH = "Swedish"
    SYRIAC = "Syriac"
    TAGALOG = "Tagalog"
    TAHITIAN = "Tahitian"
    TAI_OTHER = "Tai (Other)"
    TAJIK = "Tajik"
    TAMASHEK = "Tamashek"
    TAMIL = "Tamil"
    TATAR = "Tatar"
    TELUGU = "Telugu"
    TEMNE = "Temne"
    TERENA = "Terena"
    TETUM = "Tetum"
    THAI = "Thai"
    TIBETAN = "Tibetan"
    TIGRE = "Tigre"
    TIGRINYA = "Tigrinya"
    TIV = "Tiv"
    TLINGIT = "Tlingit"
    TOK_PISIN = "Tok Pisin"
    TOKELAUAN = "Tokelauan"
    TONGA_NYASA = "Tonga (Nyasa)"
    TONGAN = "Tongan"
    TRUK = "Truk"
    TSONGA = "Tsonga"
    TSWANA = "Tswana"
    TUMBUKA = "Tumbuka"
    TUPI_LANGUAGES = "Tupi languages"
    TURKISH = "Turkish"
    TURKISH_OTTOMAN = "Turkish, Ottoman"
    TURKMEN = "Turkmen"
    TUVALUAN = "Tuvaluan"
    TUVINIAN = "Tuvinian"
    TWI = "Twi"
    UDMURT = "Udmurt"
    UGARITIC = "Ugaritic"
    UIGHUR = "Uighur"
    UKRAINIAN = "Ukrainian"
    UMUNDU = "Umbundu"
    UNDETERMINED = "Undetermined"
    URDU = "Urdu"
    UZBEK = "Uzbek"
    VAI = "Vai"
    VENDA = "Venda"
    VIETNAMESE = "Vietnamese"
    VOLAPUK = "Volapuk"
    VOTIC = "Votic"
    WAKASHAN_LANGUAGES = "Wakashan languages"
    WALAMO = "Walamo"
    WALLOON = "Walloon"
    WARAY = "Waray"
    WELSH = "Welsh"
    WOLOF = "Wolof"
    XHOSA = "Xhosa"
    YAKUT = "Yakut"
    YAO_AFRICA = "Yao (Africa)"
    YAPESE = "Yapese"
    YIDDISH = "Yiddish"
    YORUBA = "Yoruba"
    YUPIK_LANGUAGES = "Yupik languages"
    ZANDE = "Zande"
    ZAPOTEC = "Zapotec"
    ZENAGA = "Zenaga"
    ZHUANG = "Zhuang"
    ZULU = "Zulu"
    ZUNI = "Zuni"


class DateRange(BaseModel):
    """
    Represents a publication date range.
    """
    start_year: Optional[int] = Field(default=None, alias="startYear")
    end_year: Optional[int] = Field(default=None, alias="endYear")


class NsisQtSchemaFacettes(BaseModel):
    """
    Structured output for facet extraction.

    The LLM returns a JSON object containing:
    - mediaForms: List of media type filters
    - contentGenres: List of content genre filters
    - authorNames: List of author name filters
    - languages: List of language filters
    - dateRange: Date range filter (startYear, endYear)
    - topicsInOriginalLanguage: Subject headings in original language
    - topicsInEnglish: Subject headings translated to English
    """
    media_forms: List[MediaForms] = Field(
        default_factory=list,
        alias="mediaForms",
        description="List of media form types"
    )

    content_genres: List[ContentGenre] = Field(
        default_factory=list,
        alias="contentGenres",
        description="List of content genre types"
    )

    author_names: List[str] = Field(
        default_factory=list,
        alias="authorNames",
        description="List of specific author names extracted from the request"
    )

    languages: List[Language] = Field(
        default_factory=list,
        description="The languages of the library media the USER is looking for."
    )

    date_range: Optional[DateRange] = Field(
        default=None,
        alias="dateRange",
        description="The publication period / date range of the library media the USER is looking for."
    )

    language_of_original_request: Optional[Language] = Field(
        default=None,
        alias="languageOfOriginalRequest",
        description="The language of the original request"
    )

    topics_in_original_language: List[str] = Field(
        default_factory=list,
        alias="topicsInOriginalLanguage",
        description="List of topics/subject headings in their original language (German, etc.)"
    )

    topics_in_english: List[str] = Field(
        default_factory=list,
        alias="topicsInEnglish",
        description="List of topics/subject headings translated to English"
    )

    class Config:
        populate_by_name = True
