# -*- coding: utf-8 -*-
# =============================================================================
# test_corpus_qe.py
# =============================================================================
#
# Author:      Dorian Grosch
# E-Mail:      dorian.grosch@sbb.spk-berlin.de
# Institution: Staatsbibliothek zu Berlin
#
# =============================================================================

library_media_query_corpus = {
    "schema": ["id", "persona", "subject", "media_type", "query_en", "query_de"],
    "queries": [
        ("Q001", "school_child", "dinosaurs", "book", "Easy books about dinosaurs with lots of pictures", "Einfache Bücher über Dinosaurier mit vielen Bildern"),
        ("Q002", "school_child", "space", "book", "Children's books about planets and astronauts", "Kinderbücher über Planeten und Astronauten"),
        ("Q003", "school_child", "animals", "audiobook", "Audiobooks about wild animals for kids", "Hörbücher über wilde Tiere für Kinder"),
        ("Q004", "school_child", "mythology", "graphic_novel", "Greek mythology graphic novels for children", "Graphic Novels über griechische Mythologie für Kinder"),
        ("Q005", "school_child", "science_experiments", "book", "Simple science experiment books for elementary school", "Einfache Bücher mit Wissenschaftsexperimenten für die Grundschule"),
        ("Q006", "school_child", "friendship", "fiction", "Funny stories about friendship for 8 year olds", "Lustige Geschichten über Freundschaft für 8-Jährige"),
        ("Q007", "school_child", "homework", "reference", "Kids encyclopedia for homework about oceans", "Kinderlexikon für Hausaufgaben über Ozeane"),
        ("Q008", "school_child", "fairy_tales", "book", "Fairy tales from around the world for children", "Märchen aus aller Welt für Kinder"),
        ("Q009", "school_child", "robots", "book", "Books about robots and how they work for kids", "Bücher über Roboter und wie sie funktionieren für Kinder"),
        ("Q010", "school_child", "sports", "biography", "Children's biographies of famous soccer players", "Kinderbiografien berühmter Fußballspieler"),
        ("Q011", "school_child", "drawing", "instructional_book", "How to draw animals step by step for kids", "Tiere Schritt für Schritt zeichnen lernen für Kinder"),
        ("Q012", "school_child", "mystery", "fiction", "Mystery chapter books for children who like puzzles", "Detektiv-Kinderbücher für Kinder, die Rätsel mögen"),
        ("Q013", "school_child", "weather", "book", "Books explaining thunderstorms for children", "Bücher, die Gewitter für Kinder erklären"),
        ("Q014", "school_child", "music", "sheet_music", "Easy piano songs for beginners and kids", "Einfache Klavierlieder für Anfänger und Kinder"),
        ("Q015", "school_child", "comics", "comic", "Age appropriate comic books for 10 year olds", "Altersgerechte Comics für 10-Jährige"),
        ("Q016", "school_child", "history", "book", "Children's books about ancient Egypt", "Kinderbücher über das alte Ägypten"),
        ("Q017", "school_child", "coding", "book", "Coding books for kids using Scratch", "Programmierbücher für Kinder mit Scratch"),
        ("Q018", "school_child", "nature", "field_guide", "Bird identification guide for children", "Vogelführer zum Bestimmen für Kinder"),
        ("Q019", "school_child", "feelings", "picture_book", "Picture books about feeling angry and calming down", "Bilderbücher über Wut und Beruhigung"),
        ("Q020", "school_child", "multilingual", "book", "Bilingual English German picture books for children", "Zweisprachige Bilderbücher Englisch Deutsch für Kinder"),

        ("Q021", "teenager", "young_adult_fantasy", "fiction", "YA fantasy books with strong female main characters", "Jugend-Fantasybücher mit starken weiblichen Hauptfiguren"),
        ("Q022", "teenager", "exam_prep", "study_guide", "Study guides for high school chemistry exams", "Lernhilfen für Chemieprüfungen in der Oberstufe"),
        ("Q023", "teenager", "mental_health", "book", "Books for teenagers about anxiety and stress", "Bücher für Jugendliche über Angst und Stress"),
        ("Q024", "teenager", "climate_change", "documentary", "Documentaries about climate change for teens", "Dokumentationen über Klimawandel für Jugendliche"),
        ("Q025", "teenager", "career_choice", "book", "Books about choosing a career after school", "Bücher zur Berufswahl nach der Schule"),
        ("Q026", "teenager", "manga", "manga", "Manga series like Naruto but available in the library", "Manga-Reihen ähnlich wie Naruto, die in der Bibliothek verfügbar sind"),
        ("Q027", "teenager", "coding", "ebook", "Beginner Python ebooks for teenagers", "Python-E-Books für Anfänger und Jugendliche"),
        ("Q028", "teenager", "romance", "fiction", "Clean romance novels for high school readers", "Unaufdringliche Liebesromane für Jugendliche"),
        ("Q029", "teenager", "history", "nonfiction", "Books about World War II for a school project", "Bücher über den Zweiten Weltkrieg für ein Schulprojekt"),
        ("Q030", "teenager", "music_production", "book", "Library books about making music on a laptop", "Bibliotheksbücher über Musikproduktion am Laptop"),
        ("Q031", "teenager", "gaming", "magazine", "Magazines or books about video game design", "Zeitschriften oder Bücher über Videospieldesign"),
        ("Q032", "teenager", "identity", "memoir", "Teen memoirs about finding your identity", "Jugendliche Memoirs über Identitätsfindung"),
        ("Q033", "teenager", "sports", "training_book", "Basketball training books for high school players", "Basketball-Trainingsbücher für Schüler in der Oberstufe"),
        ("Q034", "teenager", "art", "instructional_book", "Books for learning digital drawing and character design", "Bücher zum Lernen von digitalem Zeichnen und Charakterdesign"),
        ("Q035", "teenager", "debate", "database", "Reliable sources for a debate about social media", "Zuverlässige Quellen für eine Debatte über soziale Medien"),
        ("Q036", "teenager", "dystopia", "fiction", "Dystopian novels similar to The Hunger Games", "Dystopische Romane ähnlich wie Die Tribute von Panem"),
        ("Q037", "teenager", "language_learning", "audiobook", "Spanish learning audiobooks for beginners", "Spanisch-Hörbücher für Anfänger"),
        ("Q038", "teenager", "science_fair", "book", "Science fair project books for high school students", "Bücher mit Ideen für Jugend-forscht- oder Schul-Wissenschaftsprojekte"),
        ("Q039", "teenager", "poetry", "collection", "Modern poetry collections teenagers might actually like", "Moderne Gedichtsammlungen, die Jugendliche wirklich mögen könnten"),
        ("Q040", "teenager", "college_prep", "guide", "Books about applying to university and writing essays", "Bücher über Universitätsbewerbungen und Motivationsschreiben"),

        ("Q041", "undergraduate_student", "academic_writing", "guide", "Books on academic writing for first year university students", "Bücher über wissenschaftliches Schreiben für Studienanfänger"),
        ("Q042", "undergraduate_student", "statistics", "textbook", "Introductory statistics textbooks with practice problems", "Einführende Statistik-Lehrbücher mit Übungsaufgaben"),
        ("Q043", "undergraduate_student", "psychology", "database", "Peer reviewed articles on sleep and memory", "Peer-Review-Artikel über Schlaf und Gedächtnis"),
        ("Q044", "undergraduate_student", "sociology", "ebook", "Ebooks about social inequality in urban areas", "E-Books über soziale Ungleichheit in städtischen Räumen"),
        ("Q045", "undergraduate_student", "economics", "textbook", "Beginner macroeconomics books that explain inflation clearly", "Makroökonomie-Bücher für Anfänger, die Inflation verständlich erklären"),
        ("Q046", "undergraduate_student", "philosophy", "primary_source", "English translations of Plato's Republic", "Englische Übersetzungen von Platons Politeia"),
        ("Q047", "undergraduate_student", "film_studies", "film", "Classic silent films for a film studies class", "Klassische Stummfilme für ein Filmwissenschaftsseminar"),
        ("Q048", "undergraduate_student", "biology", "textbook", "Cell biology textbooks with diagrams and online access", "Zellbiologie-Lehrbücher mit Abbildungen und Online-Zugang"),
        ("Q049", "undergraduate_student", "computer_science", "book", "Data structures and algorithms books for beginners", "Bücher über Datenstrukturen und Algorithmen für Anfänger"),
        ("Q050", "undergraduate_student", "political_science", "journal_article", "Recent articles on voting behavior among young adults", "Aktuelle Artikel zum Wahlverhalten junger Erwachsener"),
        ("Q051", "undergraduate_student", "literature", "criticism", "Literary criticism on Mary Shelley's Frankenstein", "Literaturkritik zu Mary Shelleys Frankenstein"),
        ("Q052", "undergraduate_student", "nursing", "handbook", "Evidence based nursing handbooks for clinical practice", "Evidenzbasierte Pflegehandbücher für die klinische Praxis"),
        ("Q053", "undergraduate_student", "law", "casebook", "Introductory constitutional law casebooks", "Einführende Fallbücher zum Verfassungsrecht"),
        ("Q054", "undergraduate_student", "engineering", "textbook", "Statics textbooks with solved examples", "Technische-Mechanik-Statik-Lehrbücher mit gelösten Beispielen"),
        ("Q055", "undergraduate_student", "art_history", "image_database", "High resolution images of Renaissance paintings for study", "Hochauflösende Bilder von Renaissance-Gemälden zum Lernen"),
        ("Q056", "undergraduate_student", "medicine", "anatomy_atlas", "Human anatomy atlases for medical students", "Anatomieatlanten des Menschen für Medizinstudierende"),
        ("Q057", "undergraduate_student", "education", "book", "Books about inclusive classroom teaching methods", "Bücher über inklusiven Unterricht"),
        ("Q058", "undergraduate_student", "environmental_science", "report", "Reports on renewable energy policy in Europe", "Berichte zur Politik erneuerbarer Energien in Europa"),
        ("Q059", "undergraduate_student", "business", "case_study", "Business case studies about startup failure", "Business-Fallstudien über das Scheitern von Start-ups"),
        ("Q060", "undergraduate_student", "citation", "style_guide", "APA 7 citation manuals and examples", "APA-7-Zitierhandbücher und Beispiele"),

        ("Q061", "graduate_student", "research_methods", "book", "Advanced qualitative research methods books", "Fortgeschrittene Bücher zu qualitativen Forschungsmethoden"),
        ("Q062", "graduate_student", "systematic_review", "guide", "Guides for conducting a systematic literature review", "Leitfäden zur Durchführung einer systematischen Literaturrecherche"),
        ("Q063", "graduate_student", "machine_learning", "journal_article", "Recent survey papers on explainable AI", "Aktuelle Übersichtsartikel zu erklärbarer KI"),
        ("Q064", "graduate_student", "public_health", "dataset", "Datasets about vaccination rates by region", "Datensätze zu Impfquoten nach Region"),
        ("Q065", "graduate_student", "linguistics", "corpus", "Spoken language corpora for discourse analysis", "Korpora gesprochener Sprache für Diskursanalyse"),
        ("Q066", "graduate_student", "history", "archive", "Digitized primary sources on women in the labor movement", "Digitalisierte Primärquellen zu Frauen in der Arbeiterbewegung"),
        ("Q067", "graduate_student", "neuroscience", "journal_article", "Review articles on neuroplasticity after stroke", "Übersichtsartikel zu Neuroplastizität nach Schlaganfall"),
        ("Q068", "graduate_student", "urban_planning", "map", "Historical city maps for urban development research", "Historische Stadtpläne für Forschung zur Stadtentwicklung"),
        ("Q069", "graduate_student", "anthropology", "ethnography", "Ethnographies about migration and border communities", "Ethnografien über Migration und Grenzgemeinschaften"),
        ("Q070", "graduate_student", "finance", "database", "Financial databases with company balance sheet data", "Finanzdatenbanken mit Bilanzdaten von Unternehmen"),
        ("Q071", "graduate_student", "theology", "manuscript", "Critical editions of medieval biblical commentaries", "Kritische Editionen mittelalterlicher Bibelkommentare"),
        ("Q072", "graduate_student", "chemistry", "protocol", "Laboratory protocols for organic synthesis reactions", "Laborprotokolle für organische Synthesereaktionen"),
        ("Q073", "graduate_student", "education_policy", "dissertation", "Dissertations on standardized testing and equity", "Dissertationen über standardisierte Tests und Chancengerechtigkeit"),
        ("Q074", "graduate_student", "digital_humanities", "ebook", "Books on text mining methods for humanities research", "Bücher über Text-Mining-Methoden in den Geisteswissenschaften"),
        ("Q075", "graduate_student", "statistics", "software_manual", "R manuals for multilevel modeling", "R-Handbücher für Mehrebenenmodelle"),
        ("Q076", "graduate_student", "musicology", "score", "Full scores of Mahler symphonies for analysis", "Partituren von Mahlers Sinfonien für Analysen"),
        ("Q077", "graduate_student", "criminology", "journal_article", "Empirical studies on restorative justice programs", "Empirische Studien zu Programmen der Restorative Justice"),
        ("Q078", "graduate_student", "architecture", "image_archive", "Architectural drawings of Bauhaus buildings", "Architekturzeichnungen von Bauhaus-Gebäuden"),
        ("Q079", "graduate_student", "gender_studies", "book", "Intersectional feminist theory books", "Bücher zur intersektionalen feministischen Theorie"),
        ("Q080", "graduate_student", "research_impact", "database", "Citation databases for tracking my thesis topic", "Zitationsdatenbanken zur Verfolgung meines Masterarbeitsthemas"),

        ("Q081", "professor", "course_preparation", "textbook", "Textbooks for an introductory environmental ethics course", "Lehrbücher für einen Einführungskurs in Umweltethik"),
        ("Q082", "professor", "open_educational_resources", "oer", "Open access materials for teaching linear algebra", "Open-Access-Materialien für die Lehre in Linearer Algebra"),
        ("Q083", "professor", "research", "journal_article", "Latest journal articles on CRISPR off target effects", "Neueste Fachartikel zu Off-Target-Effekten von CRISPR"),
        ("Q084", "professor", "grant_writing", "guide", "Books on writing successful research grant proposals", "Bücher über erfolgreiche Forschungsanträge"),
        ("Q085", "professor", "pedagogy", "book", "Scholarship on active learning in large lectures", "Forschungsliteratur zu aktivem Lernen in großen Vorlesungen"),
        ("Q086", "professor", "classics", "critical_edition", "Critical editions of Homer's Iliad with commentary", "Kritische Ausgaben von Homers Ilias mit Kommentar"),
        ("Q087", "professor", "econometrics", "working_paper", "Working papers on causal inference in labor economics", "Working Papers zu kausaler Inferenz in der Arbeitsökonomie"),
        ("Q088", "professor", "climate_science", "dataset", "Climate model datasets for regional temperature projections", "Klimamodelldatensätze für regionale Temperaturprojektionen"),
        ("Q089", "professor", "media_studies", "archive", "Archives of early television advertisements", "Archive früher Fernsehwerbung"),
        ("Q090", "professor", "sabbatical", "book", "Recent monographs on transnational modernism", "Aktuelle Monografien zum transnationalen Modernismus"),
        ("Q091", "professor", "mathematics", "journal", "Topology journals with articles on knot theory", "Topologie-Zeitschriften mit Artikeln zur Knotentheorie"),
        ("Q092", "professor", "sociology", "data", "Longitudinal social survey data for inequality research", "Längsschnittdaten sozialer Umfragen für Ungleichheitsforschung"),
        ("Q093", "professor", "biology", "protocol", "Protocols for single cell RNA sequencing analysis", "Protokolle für die Analyse von Single-Cell-RNA-Sequencing"),
        ("Q094", "professor", "history", "microfilm", "Newspaper microfilms from the 1930s", "Zeitungs-Mikrofilme aus den 1930er-Jahren"),
        ("Q095", "professor", "copyright", "guide", "Library guides about copyright for course readings", "Bibliotheksleitfäden zum Urheberrecht für Kurslektüre"),
        ("Q096", "professor", "philosophy", "book", "Recent books on philosophy of artificial intelligence", "Aktuelle Bücher zur Philosophie der künstlichen Intelligenz"),
        ("Q097", "professor", "medicine", "clinical_guideline", "Clinical guidelines on hypertension management", "Klinische Leitlinien zur Behandlung von Bluthochdruck"),
        ("Q098", "professor", "library_acquisitions", "monograph", "Recommend monographs for a graduate seminar on decolonization", "Monografien für ein Graduiertenseminar zur Dekolonisierung empfehlen"),
        ("Q099", "professor", "digital_preservation", "manual", "Standards for preserving born digital research materials", "Standards zur Archivierung genuin digitaler Forschungsmaterialien"),
        ("Q100", "professor", "conference", "proceedings", "Conference proceedings on human computer interaction from last year", "Tagungsbände zu Mensch-Computer-Interaktion aus dem letzten Jahr"),

        ("Q101", "teacher", "lesson_planning", "book", "Picture books for teaching kindness in first grade", "Bilderbücher zum Thema Freundlichkeit in der ersten Klasse"),
        ("Q102", "teacher", "history", "primary_source", "Primary sources for teaching the civil rights movement", "Primärquellen für den Unterricht zur Bürgerrechtsbewegung"),
        ("Q103", "teacher", "science", "experiment_book", "Safe classroom science experiments for middle school", "Sichere Experimente für den naturwissenschaftlichen Unterricht in der Mittelstufe"),
        ("Q104", "teacher", "literature", "class_set", "Class sets of short novels for reluctant readers", "Klassensätze kurzer Romane für leseschwache Schüler"),
        ("Q105", "teacher", "media_literacy", "curriculum", "Curriculum materials for teaching fake news and media literacy", "Unterrichtsmaterialien zu Fake News und Medienkompetenz"),
        ("Q106", "teacher", "special_education", "guide", "Books about supporting students with dyslexia", "Bücher zur Unterstützung von Schülern mit Legasthenie"),
        ("Q107", "teacher", "math", "activity_book", "Hands on geometry activities for fifth grade", "Praktische Geometrie-Aktivitäten für die fünfte Klasse"),
        ("Q108", "teacher", "language_learning", "graded_reader", "Easy German readers for English speaking teens", "Einfache deutsche Lektüren für englischsprachige Jugendliche"),
        ("Q109", "teacher", "art", "video", "Videos about famous artists for classroom use", "Videos über berühmte Künstler für den Unterricht"),
        ("Q110", "teacher", "social_emotional_learning", "book", "Books for teaching conflict resolution to children", "Bücher zum Unterrichten von Konfliktlösung bei Kindern"),
        ("Q111", "teacher", "geography", "map", "Printable maps for teaching European countries", "Druckbare Karten für den Unterricht zu europäischen Ländern"),
        ("Q112", "teacher", "music", "songbook", "Songbooks for elementary school choir", "Liederbücher für den Grundschulchor"),
        ("Q113", "teacher", "environment", "lesson_plan", "Lesson plans about recycling and waste reduction", "Unterrichtspläne zu Recycling und Abfallvermeidung"),
        ("Q114", "teacher", "drama", "script", "Short plays for middle school drama club", "Kurze Theaterstücke für die Theater-AG der Mittelstufe"),
        ("Q115", "teacher", "world_religions", "book", "Balanced books for teaching world religions", "Ausgewogene Bücher für den Unterricht über Weltreligionen"),
        ("Q116", "teacher", "technology", "guide", "Teacher guides for using tablets in the classroom", "Lehrerhandbücher zur Nutzung von Tablets im Unterricht"),
        ("Q117", "teacher", "assessment", "book", "Books about formative assessment strategies", "Bücher über formative Bewertungsstrategien"),
        ("Q118", "teacher", "bilingual_education", "book", "Resources for bilingual German English classrooms", "Materialien für zweisprachige deutsch-englische Klassen"),
        ("Q119", "teacher", "poetry", "anthology", "Poetry anthologies suitable for high school students", "Gedichtanthologien für Schülerinnen und Schüler der Oberstufe"),
        ("Q120", "teacher", "civic_education", "database", "Reliable sources for teaching local government", "Zuverlässige Quellen für den Unterricht zur Kommunalpolitik"),

        ("Q121", "parent", "parenting", "book", "Books about positive discipline for toddlers", "Bücher über positive Erziehung bei Kleinkindern"),
        ("Q122", "parent", "child_development", "ebook", "Ebooks about language development in preschool children", "E-Books über Sprachentwicklung bei Vorschulkindern"),
        ("Q123", "parent", "bedtime", "picture_book", "Calming bedtime picture books for a 4 year old", "Beruhigende Gute-Nacht-Bilderbücher für ein 4-jähriges Kind"),
        ("Q124", "parent", "screen_time", "guide", "Parent guides about healthy screen time limits", "Elternratgeber zu gesunden Bildschirmzeit-Grenzen"),
        ("Q125", "parent", "nutrition", "cookbook", "Healthy lunchbox cookbooks for children", "Gesunde Pausenbrot-Kochbücher für Kinder"),
        ("Q126", "parent", "special_needs", "book", "Books for parents of autistic children", "Bücher für Eltern autistischer Kinder"),
        ("Q127", "parent", "grief", "picture_book", "Children's books explaining death and grief gently", "Kinderbücher, die Tod und Trauer behutsam erklären"),
        ("Q128", "parent", "homework_help", "reference", "Math help books for parents of fifth graders", "Mathe-Hilfebücher für Eltern von Fünftklässlern"),
        ("Q129", "parent", "family_travel", "travel_guide", "Family friendly travel guides for Italy", "Familienfreundliche Reiseführer für Italien"),
        ("Q130", "parent", "diversity", "picture_book", "Diverse picture books showing different family types", "Vielfältige Bilderbücher über unterschiedliche Familienformen"),
        ("Q131", "parent", "teen_parenting", "book", "Books about communicating with teenagers", "Bücher über Kommunikation mit Teenagern"),
        ("Q132", "parent", "baby_sleep", "audiobook", "Audiobooks about baby sleep routines", "Hörbücher über Schlafroutinen für Babys"),
        ("Q133", "parent", "financial_literacy", "book", "Books for teaching kids about money", "Bücher, um Kindern den Umgang mit Geld beizubringen"),
        ("Q134", "parent", "safety", "book", "Age appropriate books about body safety for children", "Altersgerechte Bücher über körperliche Sicherheit für Kinder"),
        ("Q135", "parent", "reading_level", "early_reader", "Early reader books for a child starting to read", "Erstlesebücher für ein Kind, das gerade lesen lernt"),
        ("Q136", "parent", "adoption", "picture_book", "Picture books about adoption and belonging", "Bilderbücher über Adoption und Zugehörigkeit"),
        ("Q137", "parent", "home_schooling", "curriculum", "Homeschooling resources for elementary science", "Homeschooling-Materialien für Sachkunde und Naturwissenschaften in der Grundschule"),
        ("Q138", "parent", "health", "book", "Books explaining allergies to children", "Bücher, die Allergien für Kinder erklären"),
        ("Q139", "parent", "family_history", "guide", "Beginner genealogy books for researching family history", "Genealogie-Bücher für Anfänger zur Familienforschung"),
        ("Q140", "parent", "bilingual_children", "book", "Resources for raising bilingual children", "Materialien zur zweisprachigen Erziehung von Kindern"),

        ("Q141", "job_seeker", "resume", "guide", "Resume writing books for changing careers", "Bücher zum Lebenslauf-Schreiben für einen Berufswechsel"),
        ("Q142", "job_seeker", "interviewing", "audiobook", "Audiobooks on job interview preparation", "Hörbücher zur Vorbereitung auf Vorstellungsgespräche"),
        ("Q143", "job_seeker", "career_change", "book", "Books about moving from retail work into office jobs", "Bücher über den Wechsel vom Einzelhandel in Bürojobs"),
        ("Q144", "job_seeker", "language_skills", "course", "Business English learning materials for job applications", "Business-Englisch-Lernmaterialien für Bewerbungen"),
        ("Q145", "job_seeker", "digital_skills", "ebook", "Beginner Excel ebooks for office work", "Excel-E-Books für Anfänger im Büro"),
        ("Q146", "job_seeker", "certification", "study_guide", "Project management certification study guides", "Lernhilfen für Projektmanagement-Zertifizierungen"),
        ("Q147", "job_seeker", "networking", "book", "Books about professional networking without feeling awkward", "Bücher über berufliches Netzwerken ohne peinliches Gefühl"),
        ("Q148", "job_seeker", "small_business", "guide", "How to start a small cleaning business books", "Bücher darüber, wie man ein kleines Reinigungsunternehmen gründet"),
        ("Q149", "job_seeker", "coding_bootcamp", "book", "Books for learning web development for a new career", "Bücher zum Lernen von Webentwicklung für einen neuen Beruf"),
        ("Q150", "job_seeker", "vocational_training", "directory", "Directories of local apprenticeship and training programs", "Verzeichnisse lokaler Ausbildungs- und Umschulungsprogramme"),
        ("Q151", "job_seeker", "cover_letter", "template", "Cover letter examples for administrative assistant jobs", "Anschreiben-Beispiele für Stellen als Verwaltungsassistenz"),
        ("Q152", "job_seeker", "career_assessment", "workbook", "Career assessment workbooks for adults", "Arbeitsbücher zur Berufsorientierung für Erwachsene"),
        ("Q153", "job_seeker", "remote_work", "book", "Books about finding legitimate remote work", "Bücher darüber, wie man seriöse Remote-Arbeit findet"),
        ("Q154", "job_seeker", "public_service", "exam_prep", "Civil service exam preparation books", "Vorbereitungsbücher für den öffentlichen Dienst"),
        ("Q155", "job_seeker", "healthcare_careers", "guide", "Guides to entry level healthcare careers", "Ratgeber zu Einstiegsberufen im Gesundheitswesen"),
        ("Q156", "job_seeker", "financial_aid", "database", "Resources for grants to pay for job training", "Quellen für Fördermittel zur Finanzierung von Weiterbildung"),
        ("Q157", "job_seeker", "workplace_rights", "book", "Books explaining employee rights in plain language", "Bücher, die Arbeitnehmerrechte verständlich erklären"),
        ("Q158", "job_seeker", "entrepreneurship", "business_plan", "Business plan templates for a food truck", "Businessplan-Vorlagen für einen Foodtruck"),
        ("Q159", "job_seeker", "public_speaking", "book", "Books to improve public speaking for interviews", "Bücher zur Verbesserung des freien Sprechens für Vorstellungsgespräche"),
        ("Q160", "job_seeker", "technology_career", "certification_guide", "CompTIA A+ study guides for beginners", "CompTIA-A+-Lernhilfen für Anfänger"),

        ("Q161", "senior_adult", "large_print", "fiction", "Large print mystery novels with gentle plots", "Großdruck-Krimis mit ruhiger Handlung"),
        ("Q162", "senior_adult", "health", "book", "Books about managing arthritis pain", "Bücher über den Umgang mit Arthritisschmerzen"),
        ("Q163", "senior_adult", "technology_help", "guide", "Simple guides for learning to use a smartphone", "Einfache Ratgeber zum Lernen der Smartphone-Nutzung"),
        ("Q164", "senior_adult", "local_history", "archive", "Old photographs and newspapers from my town", "Alte Fotos und Zeitungen aus meiner Stadt"),
        ("Q165", "senior_adult", "genealogy", "database", "Family history databases for tracing ancestors", "Familienforschungsdatenbanken zur Suche nach Vorfahren"),
        ("Q166", "senior_adult", "audiobooks", "audiobook", "Audiobooks of classic novels for long walks", "Hörbücher klassischer Romane für lange Spaziergänge"),
        ("Q167", "senior_adult", "retirement", "book", "Books about planning a meaningful retirement", "Bücher über eine sinnvolle Gestaltung des Ruhestands"),
        ("Q168", "senior_adult", "travel", "travel_guide", "Accessible travel guides for older adults", "Barrierearme Reiseführer für ältere Erwachsene"),
        ("Q169", "senior_adult", "memory", "brain_games", "Puzzle books and brain games for memory", "Rätselbücher und Denksportaufgaben für das Gedächtnis"),
        ("Q170", "senior_adult", "gardening", "book", "Gardening books for small raised beds", "Gartenbücher für kleine Hochbeete"),
        ("Q171", "senior_adult", "finance", "guide", "Plain language books about wills and estate planning", "Verständliche Bücher über Testamente und Nachlassplanung"),
        ("Q172", "senior_adult", "caregiving", "book", "Books for caring for a spouse with dementia", "Bücher zur Pflege eines Ehepartners mit Demenz"),
        ("Q173", "senior_adult", "music", "recording", "Jazz recordings from the 1950s", "Jazz-Aufnahmen aus den 1950er-Jahren"),
        ("Q174", "senior_adult", "biography", "large_print", "Large print biographies of historical figures", "Großdruck-Biografien historischer Persönlichkeiten"),
        ("Q175", "senior_adult", "exercise", "dvd", "Gentle exercise DVDs for seniors", "Sanfte Gymnastik-DVDs für Senioren"),
        ("Q176", "senior_adult", "crafts", "book", "Knitting books with easy patterns", "Strickbücher mit einfachen Mustern"),
        ("Q177", "senior_adult", "legal_help", "guide", "Consumer guides about tenant rights for seniors", "Verbraucherratgeber zu Mietrechten für Senioren"),
        ("Q178", "senior_adult", "faith", "audiobook", "Inspirational audiobooks for older adults", "Inspirierende Hörbücher für ältere Erwachsene"),
        ("Q179", "senior_adult", "book_club", "fiction", "Readable novels for a senior book club", "Gut lesbare Romane für einen Senioren-Lesekreis"),
        ("Q180", "senior_adult", "lifelong_learning", "course", "Library courses or materials for learning art history", "Bibliothekskurse oder Materialien zum Lernen von Kunstgeschichte"),

        ("Q181", "hobbyist", "cooking", "cookbook", "Cookbooks for authentic Thai home cooking", "Kochbücher für authentische thailändische Hausmannskost"),
        ("Q182", "hobbyist", "woodworking", "manual", "Beginner woodworking books with simple furniture projects", "Holzbearbeitungsbücher für Anfänger mit einfachen Möbelprojekten"),
        ("Q183", "hobbyist", "photography", "ebook", "Ebooks about nature photography techniques", "E-Books über Techniken der Naturfotografie"),
        ("Q184", "hobbyist", "board_games", "book", "Books about designing modern board games", "Bücher über das Entwerfen moderner Brettspiele"),
        ("Q185", "hobbyist", "birdwatching", "field_guide", "Field guides for identifying birds in Central Europe", "Bestimmungsbücher für Vögel in Mitteleuropa"),
        ("Q186", "hobbyist", "home_repair", "manual", "Home repair manuals for fixing plumbing leaks", "Heimwerker-Handbücher zum Reparieren von Wasserlecks"),
        ("Q187", "hobbyist", "sewing", "pattern_book", "Sewing pattern books for vintage dresses", "Schnittmusterbücher für Vintage-Kleider"),
        ("Q188", "hobbyist", "genealogy", "guide", "How to read old German handwriting for genealogy", "Alte deutsche Handschriften für die Familienforschung lesen lernen"),
        ("Q189", "hobbyist", "astronomy", "guide", "Stargazing guides for beginners with a small telescope", "Sternbeobachtungsführer für Anfänger mit kleinem Teleskop"),
        ("Q190", "hobbyist", "cycling", "map", "Cycling route maps for weekend trips", "Radwanderkarten für Wochenendausflüge"),
        ("Q191", "hobbyist", "beekeeping", "book", "Beginner books about urban beekeeping", "Anfängerbücher über Imkern in der Stadt"),
        ("Q192", "hobbyist", "language_learning", "course", "Japanese self study materials with audio", "Japanisch-Selbstlernmaterialien mit Audio"),
        ("Q193", "hobbyist", "film", "dvd", "Classic film noir movies on DVD", "Klassische Film-noir-Filme auf DVD"),
        ("Q194", "hobbyist", "podcasting", "guide", "Books about starting a podcast at home", "Bücher darüber, wie man zu Hause einen Podcast startet"),
        ("Q195", "hobbyist", "painting", "instructional_book", "Watercolor painting books for absolute beginners", "Aquarellmalerei-Bücher für absolute Anfänger"),
        ("Q196", "hobbyist", "cars", "repair_manual", "Repair manuals for older Volkswagen models", "Reparaturhandbücher für ältere Volkswagen-Modelle"),
        ("Q197", "hobbyist", "gardening", "seed_catalog", "Seed saving guides for vegetable gardeners", "Anleitungen zur Saatgutgewinnung für Gemüsegärtner"),
        ("Q198", "hobbyist", "travel_history", "book", "Books about historic walking tours in Berlin", "Bücher über historische Stadtrundgänge in Berlin"),
        ("Q199", "hobbyist", "creative_writing", "workbook", "Creative writing workbooks for science fiction stories", "Arbeitsbücher zum kreativen Schreiben von Science-Fiction-Geschichten"),
        ("Q200", "hobbyist", "home_brewing", "manual", "Home brewing manuals for making craft beer", "Handbücher zum Heimbrauen von Craft Beer"),
    ],
}
